name: Docker Image CI



on:
  push:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install Swift
    # You may pin to the exact commit or the version.
    # uses: slashmo/install-swift@425ee85feb7ed48efb3c5aff351e984d097b210d
        uses: slashmo/install-swift@v0.4.0
        with:
      # The Swift version to install.
          version: 5.7.3
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: itdogapp
          password: dckr_pat_6t5MQLFOZnJkuSwSt9ObnwFCsE4
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/x86_64
          push: true
          tags: itdogapp/mxq:latest
